steps:
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args:
      - 'init'
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args:
      - 'plan'
      - '-out=tfplan'
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args:
      - 'apply'
      - 'tfplan'
