steps:
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args:
      - 'init'
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args:
      - 'plan'
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args:
      - 'apply'
